version: '3.7'

services:

  app:
    container_name: 'Cloud_service'
    build: ./
    ports:
      - '9090:9090'
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/Cloud
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user


  database:
    image: postgres:15.1
    container_name: 'Cloud'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: Cloud
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user